module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 7
  num_classes: 18
  loss: "ce"
  ignore_index: 0
  learning_rate: 3e-3
  learning_rate_schedule_patience: 6

datamodule:
  _target_: torchgeo.datamodules.SSL4EOLBenchmarkDataModule
  root: "/mnt/SSD2/nils/torchgeo/experiments/ssl4eo/downstream"
  download: True
  sensor: "tm_toa"
  product: "cdl"
  classes: [0, 1, 5, 24, 36, 37, 61, 111, 121, 122, 131, 141, 142, 143, 152, 176, 190, 195]
  batch_size: 256
  num_workers: 2

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  min_epochs: 20
  max_epochs: 100