module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet50"
  weights: null
  in_channels: 11
  num_classes: 14
  loss: "ce"
  ignore_index: 0
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6
  weight_decay: 0.01

datamodule:
  _target_: torchgeo.datamodules.SSL4EOLBenchmarkDataModule
  root: "/mnt/SSD2/nils/torchgeo/experiments/ssl4eo/downstream"
  sensor: "oli_tirs_toa"
  product: "nlcd"
  classes: [0, 11, 21, 22, 31, 41, 42, 43, 52, 71, 81, 82, 90, 95]
  batch_size: 256
  num_workers: 4

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  min_epochs: 20
  max_epochs: 100
